### ISSUE TITLE
select and copy text from popup

### ISSUE THREAD

**Issue by minskmail** [wrwrh/leaflet-popupmovable#1]
Hi, thanks for great plugin
Probably there is  some way to select and copy whole or jast a part of the popup text. Now thats possible only when popupmovable:false 

![image](https://github.com/wrwrh/leaflet-popupmovable/assets/25284132/0e30f7d2-5751-4809-8bbe-5675fa389b5b)

**Comment by wrwrh** [comment]
This is so because it is difficult to distinguish whether the dragging is for movement or character selection.
For example, it would be compatible if only certain parts of the popup were used for dragging for movement.
I can't think of a way to do that, so if you have a PR for that, it would be welcome.

**Comment by fyyyyy** [comment]
I've done this by adding another option where you can define your own drag target.
This way, you can provide a query string to target an element (for example a popup header) in the popup. It defines the drag anchor. Probably a good idea to set `cursor: move` in the css for this element.

In the map options you can now say:

<img width="434" alt="Image" src="https://github.com/user-attachments/assets/6bab6513-2ca0-42ec-8027-7a4af540f25f" />

It defaults to p._wrapper
 

```js

  /*
  Main Function
  */
  _popupMovable(mk) {
    const p = mk.popup;
    if (p.options.popupmovable === false) return;
    //First, Embed the original position in Popup's Object.(to be used later.)
    p._wrapper.parentNode.latlng = p.getLatLng();
    //Enbed the marker option(popupAnchor) that bindding this popup.
    try {
      p._wrapper.parentNode.popupAnchor =
        p._source.options.icon.options.popupAnchor;
    } catch {
      p._wrapper.parentNode.popupAnchor = [0, 0];
    }

   // new code. use dragStartTarget or default to p._wrapper
    const dragStartTarget = this._map.options.dragStartTarget;
    const target = dragStartTarget
      ? p._container.querySelector(dragStartTarget)
      : p._wrapper;

    //Make Popup elements movable.
    new L.Draggable(p._container, target)
      .on("drag", (e) => {

```

**Comment by wrwrh** [comment]
Thank you very much for your wonderful contribution.
We are currently very busy in my business and will consider how to adopt the code once things settle down.
( I can think of a way to prepare pointers for dragging in advance, etc. )
